---
abstract: 'Mojo and HTTP based cluster framework'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
build_requires:
  File::ShareDir: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Module::Build: 0.36
  MojoX::Log::Log4perl: 0
  Mojolicious: 0.999924
  Sub::Exporter: 0
  Test::More: 0
  YAML::Syck: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious
provides:
  Clustericious:
    file: lib/Clustericious.pm
    version: 0.05
  Clustericious::App:
    file: lib/Clustericious/App.pm
  Clustericious::RouteBuilder:
    file: lib/Clustericious/RouteBuilder.pm
requires:
  File::ShareDir: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
