---
abstract: 'Mojo and HTTP based cluster framework'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
build_requires:
  Clustericious::Config: 0.01
  Clustericious::Log: 0.05
  File::ShareDir: 0
  File::Slurp: 0
  Hash::Merge: 0
  IO::Prompt: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Module::Build: 0.36
  MojoX::Log::Log4perl: 0
  Mojolicious: 2.24
  Sub::Exporter: 0
  Sys::Hostname: 0
  Test::More: 0
  YAML::Syck: 0
  YAML::XS: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious
provides:
  Clustericious:
    file: lib/Clustericious.pm
    version: 0.74
  Clustericious::App:
    file: lib/Clustericious/App.pm
  Clustericious::Command::Apache:
    file: lib/Clustericious/Command/Apache.pm
  Clustericious::Command::Generate:
    file: lib/Clustericious/Command/generate.pm
  Clustericious::Command::Generate::MbdApp:
    file: lib/Clustericious/Command/generate/MbdApp.pm
  Clustericious::Command::Hypnotoad:
    file: lib/Clustericious/Command/Hypnotoad.pm
  Clustericious::Command::Lighttpd:
    file: lib/Clustericious/Command/Lighttpd.pm
  Clustericious::Command::Nginx:
    file: lib/Clustericious/Command/Nginx.pm
  Clustericious::Command::Plackup:
    file: lib/Clustericious/Command/Plackup.pm
  Clustericious::Command::Start:
    file: lib/Clustericious/Command/Start.pm
  Clustericious::Command::Status:
    file: lib/Clustericious/Command/Status.pm
  Clustericious::Command::Stop:
    file: lib/Clustericious/Command/Stop.pm
  Clustericious::Commands:
    file: lib/Clustericious/Commands.pm
  Clustericious::Controller:
    file: lib/Clustericious/Controller.pm
  Clustericious::Plugin::AutodataHandler:
    file: lib/Clustericious/Plugin/AutodataHandler.pm
  Clustericious::Plugin::SimpleAuth:
    file: lib/Clustericious/Plugin/SimpleAuth.pm
    version: 0.01
  Clustericious::Renderer:
    file: lib/Clustericious/Renderer.pm
  Clustericious::RouteBuilder:
    file: lib/Clustericious/RouteBuilder.pm
  Clustericious::RouteBuilder::CRUD:
    file: lib/Clustericious/RouteBuilder/CRUD.pm
  Clustericious::RouteBuilder::Common:
    file: lib/Clustericious/RouteBuilder/Common.pm
  Clustericious::RouteBuilder::Proxy:
    file: lib/Clustericious/RouteBuilder/Proxy.pm
  Clustericious::RouteBuilder::Search:
    file: lib/Clustericious/RouteBuilder/Search.pm
  Clustericious::Templates:
    file: lib/Clustericious/Templates.pm
  Test::Clustericious:
    file: lib/Test/Clustericious.pm
requires:
  File::ShareDir: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 0.74
